console.log("welcome to js course");
console.log("Try programiz.pro");
var my_LastName = "prabandh";
console.log(my_LastName);
var myAge=25;
console.log(myAge);
const str = "Hello "+"World";
console.log(str);
console.log(10 + 20);
console.log(9 - "4");
console.log("java "+"script");
console.log(" " + " ");
console.log("vinod" - "thapa");
console.log(true + true);
console.log(true * false);
console.log(false + true);
console.log(false - true);
var x=5;
var y=6;
var sum = x + y;
console.log(sum);
var a=10;
var b=7;
var difference = a - b;
console.log(difference);
var c=4;
var d=8;
var product = c * d;
console.log(product);
var e=20;
var f=5;
var quotient = e / f;
console.log(quotient);
var g=10;
var h=3;
var remainder = g % h;
console.log(remainder);
var result = "hello" / 2;
console.log(result);
console.log(5 == "5");
console.log(5 === "5");
console.log(5 != "5");
console.log(5 !== "4");
console.log("hello" > 3);
console.log(5 < 3);
console.log(5 >= 5);
console.log(76476 <= 4);

